### PR TITLE
fixed linker error in echo and monitor due to missing pthread

### PR DESCRIPTION
**Pull request by firesurfer**
Added -pthread in CMakeLists.txt in tf2_ros so it compiles on a current debian testing with gcc (Debian 5.3.1-4) 5.3.1 20151219

### CODE REVIEW

**Comment by tfoote** [comment]
Thanks for the report and proposed fix. Two comments. One is that there's a deeper issue in that tf_echo does not use threads directly so it should be getting that flag exported from a lower level package. And unfortunately `-pthread` is not windows compatible so we can't merge this as is.

**Comment by firesurfer** [comment]
I changed the CMakeLists.txt so it will link to pthread only on non windows systems.

**Comment by gerkey** [comment]
It does look like c8c9a19 will make the change portable, but I agree with @tfoote that we should fix the underlying issue (in some lower package, either export `-pthread` or remove the use of pthread).

@firesurfer, are you able to determine from the failed link where the use of pthread is introduced?

**Comment by jackieokay** [comment]
Victor also reported a link error in this package and in intra_process_demo on Debian Jessie with armhf: https://github.com/ros2/common_interfaces/issues/11#issuecomment-186451997

I haven't done any investigation into this but I suspect this is related to usage of `std::thread` and//or `std::condition_variable` in rclcpp...

**Comment by firesurfer** [comment]
Oh yeah, I forgot about the error in the demos because I always remove them from the build. 
It's definitely the use of std::thread which uses internally -pthread. Some systems (Ubuntu apparently too) automatically link against pthread and some other libs. Debian doesn't.  

Unfortunately I don't know the tf2 code good enough to find the part the uses pthread without doing a lot of digging in the code.

**Pull request closed without merging**
