### PR TITLE
Use updated functions

### PR DESCRIPTION
**Pull request by esteve**
This replaces the deprecated functions with the correct ones.

### CODE REVIEW

**Comment by esteve** [comment]
CI:

http://ci.ros2.org/job/ci_linux/845/
http://ci.ros2.org/job/ci_osx/708/
http://ci.ros2.org/job/ci_windows/917/

**Comment by esteve** [comment]
The warnings are fixed on Linux, waiting for OSX and Windows:

http://ci.ros2.org/job/ci_linux/845/warnings17Result/fixed/

**Comment by esteve** [comment]
Warnings fixed on OSX:

http://ci.ros2.org/job/ci_osx/708/warnings7Result/fixed/

**Comment by esteve** [comment]
And the warnings fixed on Windows:

http://ci.ros2.org/job/ci_windows/917/warnings34Result/fixed/

**Comment by tfoote** [comment]
lgtm

**Pull request merged**
