### PR TITLE
add mode to subscribe only static_tf to tf2_ros

### PR DESCRIPTION
**Pull request by yukkysaito**
Even if we want to use only static_tf, tf is also forced to subscribe, so the computational cost becomes an issue. Added mode to subscribe only static_tf.

### CODE REVIEW

**Comment by tfoote** [comment]
I don't want to break the assumptions about completeness for an arbitrary listener. In your case some or most things may work with just the static transforms. However in many cases no transforms will be available.

If you are worried about computational costs of subscribing I suggest that you take a look at using the tf2_ros buffer server and buffer client where you can have a single entity maintain the buffer and query it remotely via an action API.

**Comment by yukkysaito** [comment]
Thank you!
Is there sample code somewhere?

**Comment by yukkysaito** [comment]
I need to call tf at 200 Hz. Isn't the calculation cost large when using action API?

**Comment by tfoote** [comment]
The tests provide relatively simple examples:

https://github.com/ros/geometry2/blob/melodic-devel/test_tf2/test/test_buffer_client.cpp
https://github.com/ros/geometry2/blob/melodic-devel/test_tf2/test/test_buffer_client.py

The server you can instanciate a standalone node or your own instance like this: 
https://github.com/ros/geometry2/blob/melodic-devel/test_tf2/test/test_buffer_server.cpp


The query itself isn't any more expensive, though there is the overhead of sending and receiving the action request and response. It might be able to support 200Hz depending on your system. But I'll point out that 200Hz seems high for a system that you're attempting to model using only static transforms.

**Comment by gbiggs** [comment]
Thanks for the input, Tully. Unfortunately @yukkysaito has muddled two issues together.

Since this is something that the wider community can probably help with, I've [made a question](https://answers.ros.org/question/320231/tf2-patterns-for-high-update-rates/) explaining what we actually need to collect possible solutions.

**Pull request closed without merging**
