### PR TITLE
Added WrenchStamped transformation (#302)

### PR DESCRIPTION
**Pull request by destogl**
* Added doTransformation for geometry_msgs/Wrench

* Added python implementation of Wrench transform

### CODE REVIEW

**Comment by destogl** [comment]
@tfoote : This is lost commit from #308 which is not added into #309.

**Comment by destogl** [comment]
I do not understand the build error, especially because it works on all computers in our lab... 

Has anyone an idea?

**Comment by kartikmohta** [comment]
@destogl The error is most likely due to the `>>` in your `boost::array` declarations. You need to add a space between the two `>` since C++11 is not enabled for these builds.

**Comment by tfoote** [comment]
With this failing CI I haven't spent time to review it. @kartikmohta suggestion sounds likely for a fix. I'll review it once it's passing CI.

**Comment by destogl** [comment]
@kartikmohta Thank you for your help!

@tfoote Now is ready for review. Except the `std::array` to `boost::array` change the code is already merged and released in melodic. Thanks!

**Review by tfoote — APPROVED** [review]
Thanks for iterating on this. It looks good to me now.

**Pull request merged**
