### PR TITLE
tf2_geometry_msgs added doTransform implementations for not stamped P…

### PR DESCRIPTION
**Pull request by cwecht**
…oint, Quaterion, Pose and Vector3 message types

### CODE REVIEW

**Comment by tfoote** [comment]
Can you explain how you're using these methods? The value of the doTransform API is that it can be used automatically to make sure that data is in the right coordinate frame. Are you calling this directly?

**Comment by cwecht** [comment]
Yes, I use them directly. They are useful to implement doTransform methods for other (custom) messages.

**Comment by tfoote** [comment]
Ok, I guess it doesn't hurt to have them available. Could you add some basic unit tests to verify that they're working correctly and continue to work correctly in the future?

**Review by tfoote — CHANGES_REQUESTED** [review]
Overall lgtm, it just needs some test coverage.

**Review by tfoote — APPROVED** [review]

**Pull request merged**
