### PR TITLE
Remove an unused variable from the tf2_eigen test.

### PR DESCRIPTION
**Pull request by clalancette**
While we are in here, also kill off some trailing whitespace.

Signed-off-by: Chris Lalancette <clalancette@osrfoundation.org>

### CODE REVIEW

**Comment by clalancette** [comment]
The kinetic build is "unstable", but in the same way that all previous builds are; it looks like it mostly comes from the eigen compatibility stuff for older distributions.  So I don't think we need to worry about that one w.r.t. this pull request.

The jade one also is "unstable", for the same reason as the kinetic one.  The odd thing is that all the previous (and subsequent) builds are marked green, while just this one is flagged for being unstable.  Not sure what is going on there.

**Comment by mikaelarguedas** [comment]
The jobs are marked as unstable if there are compiler warning only since kinetic (so not for Jade and Indigo).
The jade failure is unrelated to the warning, it's due to a test failure

**Comment by clalancette** [comment]
Oh, right, now I see.  I must have clicked on the wrong thing before.  Thanks for the heads up.  That failing test looks unrelated to this PR; tf2_ros doesn't depend on tf2_eigen in any way, and I didn't touch any other code that would change that (as far as I can tell).

**Comment by mikaelarguedas** [comment]
Yes it looks like a flaky test based on the job history. The compiler warning should be fixed though because otherwise the maintainer will receive an email for every PR opened and commit added to this repo

**Comment by clalancette** [comment]
Yeah, I agree.  @k-okada ended up doing a fairly nice solution for eigen_stl_containers; I'll look at porting that over to tf2_eigen.

In any case, that problem is independent of this PR, so we can address it separately.

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Pull request merged**
