### PR TITLE
filters: fix unsupported old messages with frame_id starting with '/'

### PR DESCRIPTION
**Pull request by vrabaud**
This is useful for navigation that has tests relying on old rosbags
whose messages have frames starting with '/' but I believe it is
useful to anybody for backward compatibility

Connects to #80

### CODE REVIEW

**Comment by vrabaud** [comment]
any problem with that one ?

**Comment by tfoote** [comment]
tf2 is supposed to not use '/' prefixed names. We tried to design tf2 to not be doing this sort of backwards compatibility logic. The glue layers from tf to tf2 all strip the slashes conditionally, so the logic is only in the backwards compatability layers. New code in tf2 should never encounter frame_ids with slashes. Recorded bagfiles are a problem, as the frame_ids are baked in. It makes sense for backwards compatibility to strip the slash on receipt. Are the target frames sent from bag files?

**Comment by vrabaud** [comment]
yop, they are. Then again, I see some slash stripping in tf2: https://github.com/ros/geometry_experimental/blob/indigo-devel/tf2/src/buffer_core.cpp#L107
It's just that message_filters are not as core as buffer_core and I believe they got forgotten.
(just rebased btw)

**Comment by tfoote** [comment]
Yeah, lets make it happen. The stripping can always be removed at some much later date. Thanks for the rebase.

**Pull request merged**
