### PR TITLE
Revert "officialize toMsg and fromMsg by adding them to convert"

### PR DESCRIPTION
**Pull request by vrabaud**
This reverts commit ea87ea91e67b5f1ed28134cafeea8a1c6329e7ec.

We just don't want to break the ABI

### CODE REVIEW

**Comment by vrabaud** [comment]
Hi, sorry for the inconvenience but with the latest ABI breakage in image_pipeline, I'd rather not get that commit in, cf http://www.ros.org/reps/rep-0009.html

It is just a cleanup anyway: for K-turtle, we might as well remove the toMsg and fromMsg for message functions (as they are already handled by the `convert` function).

**Comment by mikeferguson** [comment]
tf2 is not >= version 1.0 though, right? so ABI breakage is fine, right? We break the ABI/API of moveit all the time....

**Comment by tfoote** [comment]
Since we're not making guarantees about ABI we don't need to be super strict. 

Can we do it where we add the automatic methods which is just adding symbols but only remove the old style methods later?

**Comment by vrabaud** [comment]
ok, I only reverted the toMsg and fromMsg for messages as they don't make sense.

**Comment by tfoote** [comment]
looks good. thanks. I'll create a jade branch to push this back into.

**Pull request merged**
