### PR TITLE
Get yaw

### PR DESCRIPTION
**Pull request by vrabaud**
This needs #111 to be in but it provides a few useful functions when using tf2. Maybe we should have a new header like utils.h or something.

### CODE REVIEW

**Comment by vrabaud** [comment]
@Karsten1987, you must be so happy to have such a boss :)

**Comment by vrabaud** [comment]
TODO: get it to work with Stamped version of the data. Will probably wait for #111 to be merged before updating.

**Comment by tfoote** [comment]
Thanks @vrabaud that looks like a good approach. Maybe euler.h would be a good file name? Keep it relatively clearly scoped.

**Comment by vrabaud** [comment]
well, there is also getIdentity in there.

**Comment by vrabaud** [comment]
how about a utils.h that would contain getTimestamp, getFrameId, getYaw, getEulerYPR, getIdentity and have convert.h include it (for backward compatiblity) and only contain doTransform, toMsg, fromMsg and convert ?

**Comment by vrabaud** [comment]
ok, updated. @tfoote , @mikeferguson I need some advice before validating that:
- I restricted getEulerYPR and get Yaw to work with anything that can be converted to a quaternion. hence, it would not work for a Pose and such. Should I specialize for things that contain a rotation ? (I personnally think it would be wrong and it's not such a hassle to write `getEulerYPR(t.quaternion)`
- getIdentity only works for anything that can be converted to a `tf2::Transform`. Should I name it differently ? Should I specialize it for anything that has some identity (like Vector3, Quaternion) ?

**Comment by mikeferguson** [comment]
@vrabaud on the first point, that is exactly what I would expect, getEulerYPR(t.quaternion) is very clear what the intent is, and is not much more to write.

On the getIdentity() -- I don't really have a strong opinion either way. I think it is fine as-is, and if it becomes a problem later, we can add additional specializations.

**Comment by tfoote** [comment]
I agree with @mikeferguson . 

This looks pretty good. Anything else you're thinking @vrabaud ?

**Comment by vrabaud** [comment]
all I did was rename `getIdentity` to `getTransformIdentity` as I believe we might need `getQuaternionIdentity` and a few other ones.

So, all good to me.

**Comment by vrabaud** [comment]
that will be released after the indigo and jade syncs I guess ?

**Pull request merged**
