### PR TITLE
export dll and exe to correct locations

### PR DESCRIPTION
**Pull request by kejxu**
according to catkin guidelines
- http://docs.ros.org/melodic/api/catkin/html/howto/format2/building_libraries.html
- http://docs.ros.org/melodic/api/catkin/html/howto/format2/building_executables.html

### CODE REVIEW

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Review by tfoote — APPROVED** [review]
lgtm, retriggering CI due  to failing on recent rosdep issue with github urls changing.

**Comment by kejxu** [comment]
> lgtm, retriggering CI due to failing on recent rosdep issue with github urls changing.

was looking at the other pr for geometry2 and noticed the build is passing on this one, could we merge this change? thanks =)

**Comment by seanyen** [comment]
@lucasw @tfoote Hi! Hope I am pinging the correct maintainers. Can you help take a look on #361 and #365? Thanks!

**Review by rhaschke — APPROVED** [review]

**Comment by seanyen** [comment]
@tfoote Friendly ping.

**Pull request closed without merging**
