### PR TITLE
Doxygen documentation for conversion libraries update to mainpage.dox

### PR DESCRIPTION
**Pull request by jackieokay**
Adding Doxygen-style documentation to conversion libraries.

@tfoote and @mikaelarguedas, can you take a look and check for clarity and correctness? If it looks okay, I will expand on this PR by copying this documentation to the other conversion libraries.

I'm having trouble generating the documentation location (I made a Doxyfile and called doxygen in the folder for the package, but it didn't generate anything for the actual header file). Any suggestions for previewing this?

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
lgtm seems clear and having all the required information.
Regarding the doc generation I would have to try locally to let you know cause I haven't generated doxygen documentation in a while

**Comment by tfoote** [comment]
This looks good. We should plan to embed a link to the conversions overview in the autodocs too. 

We use rosdoc_lite to generate docs: http://wiki.ros.org/rosdoc_lite it uses rosdoc.yaml to get parameters for the package.

**Comment by jackieokay** [comment]
Thanks! I think `mainpage.dox` is a good place to put the Conversions overview. I assume you mean http://wiki.ros.org/tf2/Tutorials/Migration/DataConversions, let me know if that's wrong or if we think this URL is going to change after the migration is done.

**Comment by tfoote** [comment]
Yeah, the mainpage.dox for tf2 would be a good place for the conversion overview. https://github.com/ros/geometry_experimental/blob/indigo-devel/tf2/mainpage.dox

Yeah, http://wiki.ros.org/tf2/Tutorials/Migration/DataConversions is a good place to point to from the code for examples of how to use the API. And we'll want to expand that page too.

**Comment by jackieokay** [comment]
Adding Python documentation as well which is slightly different. Feel free to take a look at `tf2_kdl.py` as well as the conf.py and index.rst for that repository, which I will copy for the other packages if it looks acceptable.

**Comment by tfoote** [comment]
It looks reasonable. It would be nice if the conf.py didn't need so much boilerplate, but it's probably good to keep it all there if someone wants to tweak it in the future. 

Sorry I took one of the executors offline and it appears to have killed the indigo job @ros-pull-request-builder  build this please.

**Comment by jackieokay** [comment]
The conf.py can actually be generated by Sphinx, but in this case I copied it from tf2_ros because I didn't know how to run the generation step... I would be fine to take out all the commented lines, especially if I can find a link to better Sphix documentation and paste it at the top. I'll look into it before working on the next Python package in this repo.

**Comment by jackieokay** [comment]
How does 19906233dac7f3952812f6ba269825f158e1f832 look for new text for the landing page of the C++ Doxygen pages?

**Comment by tfoote** [comment]
I like the direct but use case driven approach. We'll want to add some more links. 

note it's tf2_ros not tf2_ros2.

I'd link to the tf2_ros::BufferInterface as the main interface for user reference and introduce the `transform` method first. Then canTransform and lookupTransform are lower level. 

It should probably flow into recommending the tf2_ros::MessageFilter http://docs.ros.org/jade/api/tf2_ros/html/c++/classtf2__ros_1_1MessageFilter.html for any use case with streaming data. 

And we should link to the documentation about data type conversions in the tf2 package documentation. 

And then also mention Exceptions that might be thrown. 

Shoot can you also add a TODO for me to document the Client/Server API too. That's a new feature that's not documented at all.

**Comment by jackieokay** [comment]
in 01adf2d I added a link to BufferClient and attempted to explain it, but I wasn't really sure about the feature since I haven't used it and, as you said, it's not yet documented... Can you take a look @tfoote?

**Comment by jackieokay** [comment]
Alright, I've gone a little crazy adding Doxygen/Sphix API documentation.

Highlights:

mainpage.dox for the tf2_ros C++ API (the landing page for the generated C++ documentation):
https://github.com/ros/geometry_experimental/pull/163/files#diff-817688e75568baa2ae353b649f5862d0

index.rst for the tf2_ros Python API (the landing page for the generated Python documentation):
https://github.com/ros/geometry_experimental/pull/163/files#diff-21b03b6499e27ba8a9351dc30c6c8135

Added Python documentation in tf2_ros.

Doxygen documentation for tf2_eigen, tf2_bullet, tf2_kdl, tf2_geometry_msgs.

Looking at #160, I'm going to flesh out the Doxygen landing page for tf to include some info about the templated data conversions next.

@mikaelarguedas We should update the links on the tutorials based on the expected location of the Python generated documentation. You can do this by running rosdoc_lite locally, but if you're busy with other tasks I can take a look.

**Comment by tfoote** [comment]
@jacquelinekay This looks great, it's a huge improvement.

Note there is one flaky test in this repo which your pr builds have hit sometimes: https://github.com/ros/geometry_experimental/issues/129

**Comment by mikaelarguedas** [comment]
Yes sorry I havent updated the links yet I waited for the doc to be ready. I'll do it right away

Some pages need a little bit of cleanup too, I'll do that right after.

I'm currently looking at porting all the tf tools to tf2 (tf_echo, tf_monitor...)
They'll need a little bit of love before they're ready to be ported commited to geometry2/tf2_tools

Otherwise my static tranform publisher in Python is not working, I guess I messed up while creating the StaticTransformPublisher python class. I have to figure out how to do the latching for the tutorial to actually work.

**Comment by tfoote** [comment]
Thanks @jacquelinekay this looks great. I've merged it and will do a more through read of it after retriggering the doc job and read the rendered output. @mikaelarguedas if you have any references they should be ready soon. I'll trigger the doc job now.

**Comment by mikaelarguedas** [comment]
sounds good to me, all references have been updated based on the
rosdoc-lite ran locally yesterday. I'll test them all once the job is done.

**Pull request merged**
