### PR TITLE
Use new-style objects in python 2

### PR DESCRIPTION
**Pull request by eric-wieser**

### CODE REVIEW

**Comment by eric-wieser** [comment]
Looks like an unrelated failure to me

**Comment by tfoote** [comment]
@ros-pull-request-builder test this please

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Comment by eric-wieser** [comment]
Thanks!

**Pull request merged**
