### PR TITLE
remove the use of slashes from topics

### PR DESCRIPTION
**Pull request by tfoote**
DDS does not support slashes. 

We have held back on developing our integrated naming design with the potential to alias ROS topics and DDS topic names.

### CODE REVIEW

**Comment by gerkey** [comment]
+1

**Comment by mikeferguson** [comment]
Out of curiosity -- when you say "does not support slashes" -- is that mean just at the beginning of the name, or throughout? That is, will we be unable to "namespace" things, such as is currently done with many drivers, like "camera/rgb/image" and "camera/rgb/image_raw" ??

**Comment by wjwwood** [comment]
This is just a temporary limitation. We have to decide on the policy for addressing in ROS 2 before committing to any solution in the code.

**Comment by tfoote** [comment]
http://ci.ros2.org/job/ci_linux/818

**Comment by wjwwood** [comment]
DDS does not allow `/` in the topics at all, but we can use another separator in place of `/`. We intend to support `/` in the ROS API's as well as namespacing, just not yet.

**Comment by mikeferguson** [comment]
thanks @wjwwood -- I wasn't sure what the story was and that was a bit concerning

**Pull request merged**
