### PR TITLE
Handle geometry_msgs/Twist and geometry_msgs/TwistStamped messages.

### PR DESCRIPTION
**Pull request by RobertBlakeAnderson**
Extension of tf2_geometry_msgs for additional message types.

I'm also of a mind to extend the tf2_sensor_msgs package and create a tf2_nav_msgs package. Let me know if you'd be interested in pulling that.

### CODE REVIEW

**Comment by RobertBlakeAnderson** [comment]
Looks like one of the tests hit a rosdep error involving the actionlib dependency.

**Comment by RobertBlakeAnderson** [comment]
I've rebased this to the current repo commit in the hope of getting it accepted. However the checks are failing in Noetic and passing in Melodic. The error message is:

`13:36:16 Traceback (most recent call last):

13:36:16   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 276, in resolve_names

13:36:16     resolved_names = resolve_for_os(

13:36:16   File "/usr/lib/python3/dist-packages/rosdep2/catkin_support.py", line 87, in resolve_for_os
13:36:16     d = view.lookup(rosdep_key)

13:36:16   File "/usr/lib/python3/dist-packages/rosdep2/lookup.py", line 200, in lookup

13:36:16     return self.rosdep_defs[rosdep_name]

13:36:16 KeyError: 'orocos_kdl'

13:36:16 During handling of the above exception, another exception occurred:

13:36:16 Traceback (most recent call last):

13:36:16   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 293, in <module>

13:36:16     main()

13:36:16   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 127, in main
13:36:16     debian_pkg_names_building = resolve_names(build_depends, **context)

13:36:16   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 279, in resolve_names

13:36:16     raise RuntimeError(
13:36:16 RuntimeError: Could not resolve the rosdep key 'orocos_kdl'

13:36:16 Build step 'Execute shell' marked build as failure`

Previously, the same error had been triggered by the actionlib key. @tfoote Any insight into what's going on here? I'm unfamiliar with Noetic.

**Comment by standmit** [comment]
@tfoote , can it be merged into the noetic branch?

**Comment by ahcorde** [comment]
This PR is targeting a [EOL distribution melodic](http://wiki.ros.org/Distributions), closing this PR, feel free to reopen this against a maintained branch

**Pull request closed without merging**
