### PR TITLE
Cherry-picking various commits from Melodic

### PR DESCRIPTION
**Pull request by rhaschke**
The current Noetic release is missing various commits from the Melodic branch, most importantly #436, which reverted #367, which in turn was causing build issues in MoveIt. For this reason, the MoveIt release into Noetic is currently blocked.
Please cherry-pick those missing commits and prepare a new release into Noetic.
Note, that the list below includes https://github.com/ros/geometry2/tree/forward_port_444.

### CODE REVIEW

**Comment by rhaschke** [comment]
@tfoote, @sloretz: This is blocking the MoveIt Noetic release. Please consider merging and releasing. Thanks.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2020-08-20/16063/1

**Review by tfoote — APPROVED** [review]
Thanks for porting these forward.

**Comment by rhaschke** [comment]
Thanks for merging, @tfoote. Could you, please, prepare a new Noetic release as well to unblock MoveIt? Thanks.

**Pull request merged**
