### PR TITLE
Solve a bug that causes a deadlock in MessageFilter

### PR DESCRIPTION
**Pull request by afakihcpr**
The deadlock happens when the following two things happen at the same instant:
- MessageFilter trying to erase a message from the queue, locks the messages_mutex_ then calls BufferCore::cancelTransformableRequest where it needs the transformable_requests_mutex_
- BufferCore upon receiving a TF callback, locks the transformable_requests_mutex_ in testTransformableRequests and goes through the list of requests where one of the callback it calls is MessageFilter::Transformable that attempts to acquire a unique_lock on message_mutex_

related to https://github.com/ros/geometry_experimental/issues/91

@tfoote @jasonimercer @efernandez @ayrton04

Backtrace:

``` bash
Thread 6 (Thread 0x7fffedc55700 (LWP 28549)):
#0  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff7a4ae4f in boost::condition_variable::wait (this=0x62e0f0, 
    m=...) at /usr/include/boost/thread/pthread/condition_variable.hpp:73
#2  0x00007ffff7a4b924 in boost::shared_mutex::unlock_upgrade_and_lock (
    this=0x62e010) at /usr/include/boost/thread/pthread/shared_mutex.hpp:503
#3  0x00007ffff7ad0272 in boost::unique_lock<boost::shared_mutex>::unique_lock
    (this=0x7fffedc54078, other=...)
    at /usr/include/boost/thread/lock_types.hpp:1046
#4  0x00007ffff7ac23fd in boost::upgrade_to_unique_lock<boost::shared_mutex>::upgrade_to_unique_lock (this=0x7fffedc54070, m_=...)
    at /usr/include/boost/thread/lock_types.hpp:1063
#5  0x00007ffff7ab261d in tf2_ros::MessageFilter<geometry_msgs::TwistWithCovarianceStamped_<std::allocator<void> > >::transformable (this=0x62df50, 
    request_handle=1358, target_frame=..., source_frame=..., time=..., 
    result=tf2::TransformAvailable)
    at /home/afakih/workspaces/rl_ws/src/geometry_experimental/tf2_ros/include/tf2_ros/message_filter.h:542
#6  0x00007ffff7b06869 in boost::_mfi::mf5<void, tf2_ros::MessageFilter<geometry_msgs::TwistWithCovarianceStamped_<std::allocator<void> > >, unsigned long, std::string const&, std::string const&, ros::Time, tf2::TransformableResult>::operator() (this=0x7fffedc54378, p=0x62df50, a1=1358, a2=..., a3=..., a4=..., 
    a5=tf2::TransformAvailable)
    at /usr/include/boost/bind/mem_fn_template.hpp:619
#7  0x00007ffff7afaa23 in boost::_bi::list6<boost::_bi::value<tf2_ros::MessageFilter<geometry_msgs::TwistWithCovarianceStamped_<std::allocator<void> > >*>, boost::arg<1>, boost::arg<2>, boost::arg<3>, boost::arg<4>, boost::arg<5> >::operator()<boost::_mfi::mf5<void, tf2_ros::MessageFilter<geometry_msgs::TwistWithCovarianceStamped_<std::allocator<void> > >, unsigned long, std::string const&, std::string const&, ros::Time, tf2::TransformableResult>, boost::_bi::list5<unsigned long&, std::string const&, std::string const&, ros::Time&, tf2::TransformableResult&> > (this=0x7fffedc54388, f=..., a=...)
    at /usr/include/boost/bind/bind.hpp:596
#8  0x00007ffff7aeded1 in boost::_bi::bind_t<void, boost::_mfi::mf5<void, tf2_ros::MessageFilter<geometry_msgs::TwistWithCovarianceStamped_<std::allocator<void> > >, unsigned long, std::string const&, std::string const&, ros::Time, tf2::TransformableResult>, boost::_bi::list6<boost::_bi::value<tf2_ros::MessageFilter<geometry_msgs::TwistWithCovarianceStamped_<std::allocator<void> > >*>, boost::arg<1>, boost::arg<2>, boost::arg<3>, boost::arg<4>, boost::arg<5> > >::operator()<unsigned long, std::string const, std::string const, ros::Time, tf2::TransformableResult> (this=0x7fffedc54378, a1=@0x7fffedc54250: 1358, a2=..., a3=..., 
    a4=..., a5=@0x7fffedc54234: tf2::TransformAvailable)
    at /usr/include/boost/bind/bind_template.hpp:174
#9  0x00007ffff7adfac4 in boost::detail::function::void_function_obj_invoker5<boost::_bi::bind_t<void, boost::_mfi::mf5<void, tf2_ros::MessageFilter<geometry_msgs::TwistWithCovarianceStamped_<std::allocator<void> > >, unsigned long, std::string const&, std::string const&, ros::Time, tf2::TransformableResult>, boost::_bi::list6<boost::_bi::value<tf2_ros::MessageFilter<geometry_msgs::TwistWithCovarianceStamped_<std::allocator<void> > >*>, boost::arg<1>, boost::arg<2>, boost::arg<3>, boost::arg<4>, boost::arg<5> > >, void, unsigned long, std::string const&, std::string const&, ros::Time, tf2::TransformableResult>::invoke (
    function_obj_ptr=..., a0=1358, a1=..., a2=..., a3=..., 
    a4=tf2::TransformAvailable)
    at /usr/include/boost/function/function_template.hpp:153
#10 0x00007ffff5556d52 in boost::function5<void, unsigned long, std::string const&, std::string const&, ros::Time, tf2::TransformableResult>::operator() (
    this=0x7fffedc54370, a0=1358, a1=..., a2=..., a3=..., 
    a4=tf2::TransformAvailable)
    at /usr/include/boost/function/function_template.hpp:767
#11 0x00007ffff554e634 in tf2::BufferCore::testTransformableRequests (
    this=0x7fffffffd568)
    at /home/afakih/workspaces/rl_ws/src/geometry_experimental/tf2/src/buffer_core.cpp:1356
#12 0x00007ffff554ad25 in tf2::BufferCore::setTransform (this=0x7fffffffd568, 
    transform_in=..., authority=..., is_static=false)
    at /home/afakih/workspaces/rl_ws/src/geometry_experimental/tf2/src/buffer_core.cpp:265
#13 0x00007ffff5edfb7d in tf2_ros::TransformListener::subscription_callback_impl (this=0x7fffffffd708, msg_evt=..., is_static=false)
    at /home/afakih/workspaces/rl_ws/src/geometry_experimental/tf2_ros/src/transform_listener.cpp:119
#14 0x00007ffff5edf96e in tf2_ros::TransformListener::subscription_callback (
    this=0x7fffffffd708, msg_evt=...)
    at /home/afakih/workspaces/rl_ws/src/geometry_experimental/tf2_ros/src/transform_listener.cpp:95
#15 0x00007ffff5ee81da in boost::_mfi::mf1<void, tf2_ros::TransformListener, ros::MessageEvent<tf2_msgs::TFMessage_<std::allocator<void> > const> const&>::operator() (this=0x622c98, p=0x7fffffffd708, a1=...)
    at /usr/include/boost/bind/mem_fn_template.hpp:165
#16 0x00007ffff5ee7691 in boost::_bi::list2<boost::_bi::value<tf2_ros::TransformListener*>, boost::arg<1> >::operator()<boost::_mfi::mf1<void, tf2_ros::TransformListener, ros::MessageEvent<tf2_msgs::TFMessage_<std::allocator<void> > const> const&>, boost::_bi::list1<boost::shared_ptr<tf2_msgs::TFMessage_<std::allocator<void> > const> const&> > (this=0x622ca8, f=..., a=...)
    at /usr/include/boost/bind/bind.hpp:313
#17 0x00007ffff5ee6b40 in boost::_bi::bind_t<void, boost::_mfi::mf1<void, tf2_ros::TransformListener, ros::MessageEvent<tf2_msgs::TFMessage_<std::allocator<void> > const> const&>, boost::_bi::list2<boost::_bi::value<tf2_ros::TransformListener*>, boost::arg<1> > >::operator()<boost::shared_ptr<tf2_msgs::TFMessage_<std::allocator<void> > const> > (this=0x622c98, a1=...)
    at /usr/include/boost/bind/bind_template.hpp:47
#18 0x00007ffff5ee5ec1 in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, tf2_ros::TransformListener, ros::MessageEvent<tf2_msgs::TFMessage_<std::allocator<void> > const> const&>, boost::_bi::list2<boost::_bi::value<tf2_ros::TransformListener*>, boost::arg<1> > >, void, boost::shared_ptr<tf2_msgs::TFMessage_<std::allocator<void> > const> const&>::invoke (function_obj_ptr=..., a0=...)
    at /usr/include/boost/function/function_template.hpp:153
#19 0x00007ffff5ee8429 in boost::function1<void, boost::shared_ptr<tf2_msgs::TFMessage_<std::allocator<void> > const> const&>::operator() (this=0x622c90, 
    a0=...) at /usr/include/boost/function/function_template.hpp:767
#20 0x00007ffff5ee7874 in boost::detail::function::void_function_obj_invoker1<boost::function<void (boost::shared_ptr<tf2_msgs::TFMessage_<std::allocator<void> > const> const&)>, void, boost::shared_ptr<tf2_msgs::TFMessage_<std::allocator<void> > const> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<tf2_msgs::TFMessage_<std::allocator<void> > const>) (
    function_obj_ptr=..., a0=...)
    at /usr/include/boost/function/function_template.hpp:153
#21 0x00007ffff5eea28c in boost::function1<void, boost::shared_ptr<tf2_msgs::TFMessage_<std::allocator<void> > const> >::operator() (this=0x622c48, a0=...)
    at /usr/include/boost/function/function_template.hpp:767
#22 0x00007ffff5ee9a82 in ros::SubscriptionCallbackHelperT<boost::shared_ptr<tf2_msgs::TFMessage_<std::allocator<void> > const> const&, void>::call (
    this=0x622c40, params=...)
    at /opt/ros/indigo/include/ros/subscription_callback_helper.h:144
#23 0x00007ffff7530495 in ros::SubscriptionQueue::call() ()
   from /opt/ros/indigo/lib/libroscpp.so
#24 0x00007ffff74eb137 in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*) () from /opt/ros/indigo/lib/libroscpp.so
#25 0x00007ffff74ebf33 in ros::CallbackQueue::callAvailable(ros::WallDuration)
    () from /opt/ros/indigo/lib/libroscpp.so
#26 0x00007ffff5ee11c7 in tf2_ros::TransformListener::dedicatedListenerThread (
    this=0x7fffffffd708)
    at /home/afakih/workspaces/rl_ws/src/geometry_experimental/tf2_ros/include/tf2_ros/transform_listener.h:80
#27 0x00007ffff5eea7fb in boost::_mfi::mf0<void, tf2_ros::TransformListener>::operator() (this=0x627638, p=0x7fffffffd708)
    at /usr/include/boost/bind/mem_fn_template.hpp:49
#28 0x00007ffff5eea578 in boost::_bi::list1<boost::_bi::value<tf2_ros::TransformListener*> >::operator()<boost::_mfi::mf0<void, tf2_ros::TransformListener>, boost::_bi::list0> (this=0x627648, f=..., a=...)
    at /usr/include/boost/bind/bind.hpp:253
#29 0x00007ffff5ee9df9 in boost::_bi::bind_t<void, boost::_mfi::mf0<void, tf2_ros::TransformListener>, boost::_bi::list1<boost::_bi::value<tf2_ros::TransformListener*> > >::operator() (this=0x627638)
    at /usr/include/boost/bind/bind_template.hpp:20
#30 0x00007ffff5ee96f8 in boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, tf2_ros::TransformListener>, boost::_bi::list1<boost::_bi::value<tf2_ros::TransformListener*> > > >::run (this=0x627480)
    at /usr/include/boost/thread/detail/thread.hpp:117
#31 0x00007ffff4ea0a4a in ?? ()
   from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
#32 0x00007ffff4c7f182 in start_thread (arg=0x7fffedc55700)
    at pthread_create.c:312
#33 0x00007ffff6a3c47d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7ffff7fb37c0 (LWP 28517)):
#0  __lll_lock_wait ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff4c81657 in _L_lock_909 ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007ffff4c81480 in __GI___pthread_mutex_lock (mutex=0x7fffffffd6a8)
    at ../nptl/pthread_mutex_lock.c:79
#3  0x00007ffff7a48e45 in pthread_mutex_lock (m=0x7fffffffd6a8)
    at /usr/include/boost/thread/pthread/mutex.hpp:61
#4  boost::mutex::lock (this=0x7fffffffd6a8)
    at /usr/include/boost/thread/pthread/mutex.hpp:113
#5  0x00007ffff7a5229c in boost::unique_lock<boost::mutex>::lock (
    this=0x7fffffffc020) at /usr/include/boost/thread/lock_types.hpp:346
#6  0x00007ffff7a50b13 in boost::unique_lock<boost::mutex>::unique_lock (
    this=0x7fffffffc020, m_=...)
    at /usr/include/boost/thread/lock_types.hpp:124
#7  0x00007ffff554dea3 in tf2::BufferCore::cancelTransformableRequest (
    this=0x7fffffffd568, handle=1358)
    at /home/afakih/workspaces/rl_ws/src/geometry_experimental/tf2/src/buffer_core.cpp:1243
#8  0x00007ffff7a9d5f2 in tf2_ros::MessageFilter<geometry_msgs::TwistWithCovarianceStamped_<std::allocator<void> > >::add (this=0x62df50, evt=...)
    at /home/afakih/workspaces/rl_ws/src/geometry_experimental/tf2_ros/include/tf2_ros/message_filter.h:394
#9  0x00007ffff7a8b11e in tf2_ros::MessageFilter<geometry_msgs::TwistWithCovarianceStamped_<std::allocator<void> > >::add (this=0x62df50, message=...)
    at /home/afakih/workspaces/rl_ws/src/geometry_experimental/tf2_ros/include/tf2_ros/message_filter.h:432
```

### CODE REVIEW

**Comment by tfoote** [comment]
@ros-pull-request-builder please test this

**Comment by tfoote** [comment]
@afakihcpr Thanks for looking into this. From a quick read it makes sense, however I'm going to need some time to dig back in. And I'm also hoping that we can find a non-boost based solution to be forwards compatible with the ROS2 version.

**Comment by mikepurvis** [comment]
@tfoote We'd like to get this merged so that we can get back on mainline tf2.

Would you consider a version that had a compile time switch to use `std::unique_lock`, `std::tuple`, etc?

**Comment by tfoote** [comment]
@mikepurvis That would be great. Unfortunately those look to be c++11 and newer [here](http://en.cppreference.com/w/cpp/thread/unique_lock). So it would need to be an `#ifdef` for Indigo and Jade support.

**Pull request merged**
