### PR TITLE
tf2_eigen: Deprecate methods using Affine3d.

### PR DESCRIPTION
**Pull request by peci1**
Based on discussion in #358 .

### CODE REVIEW

**Comment by peci1** [comment]
The tests pass, but compiling them issues deprecation warnings because they're still testing the newly deprecated functions.

**Review by tfoote — CHANGES_REQUESTED** [review]
This looks fine but we should switch the test cases before merging this. And for deprecating API's we'd need to target the changes into noetic and not pull them out from under people on the current release.

We haven't yet forked for noetic, but I'll add the milestone to keep track of this.

**Comment by ahcorde** [comment]
This PR is targeting a [EOL distribution melodic](http://wiki.ros.org/Distributions), closing this PR, feel free to reopen this against a maintained branch

**Comment by peci1** [comment]
Continued in #561.

**Pull request closed without merging**
