### PR TITLE
casted el to string in view_frames

### PR DESCRIPTION
**Pull request by g-gemignani**

### CODE REVIEW

**Comment by tfoote** [comment]
This looks reasonable. Can you share a use case where this is a problem?

**Comment by g-gemignani** [comment]
Hello,
This is a problem when you have a frame that uses a number as name.
For example, in our project we had a frame called "54". This made view_frames.py crash. 
I understand that this is a corner case but I believe that it might still happen.

**Comment by g-gemignani** [comment]
Hello,
as suggested I created a pull request for throwing an error when a not unitary quaternion is given in input to the static_transform_publisher

**Comment by tfoote** [comment]
I've cherry picked the first commit.

The check for normalization needs to have some tolerance. Expecting the value to be normalized to full double floating point precision is going to fail many things which are effectively normalized. It will take some research to determine what an appropriate tolerance would be.

**Comment by tfoote** [comment]
normalization followed up in #196

**Pull request closed without merging**
